### ISSUE TITLE
implementere funksjonalitet for å holde på hvilken bruker som reserverer/lager parkeringsplass

### ISSUE THREAD

**Issue by haros-dev** [Jonaseli/SE2020-Gruppe12#68]
e.g. ha variabel i main som holder på hvilken bruekr det er som har trykket på en reservasjonsknapp når de er inne på reserveringssiden. usikker på hvordan det skal implementeres konkret

**Comment by haros-dev** [comment]
og dette er gjort for å slippe å ha brukerId hardkodet i url

**Comment by Jonaseli** [comment]
Denne forsvinner fra MVP, så closer.
