### ISSUE TITLE
lage basic admin side

### ISSUE THREAD

**Issue by haros-dev** [Jonaseli/SE2020-Gruppe12#74]
siden skal ha samme basic nav bar som resten av prosjektet
siden skal liste opp alle parkeringsplasser, brukere, post og reservasjoner i systemet
siden skal ha to knapper, en knapp for å slette bruker og en for å banne/unbanne en bruker (trenger ikke ha funksjonaliteten enda)

**Comment by Jonaseli** [comment]
Lager en branch og jobber med denne nå
