### ISSUE TITLE
finpusse parking spot detail siden

### ISSUE THREAD

**Issue by haros-dev** [Jonaseli/SE2020-Gruppe12#77]
siden skal displaye all relevant informasjon fra parking spot
siden skal ha en Status: "Available"/"Reserved" isteden for true/false på availability
siden skal ikke vise noen ID-er (ikke relevant for bruker)

eksempel på struktur:
Gatenavn NR
POSTNR Poststed
Type: "Handicap"/"Normal"
Width: WIDTH Length: LENGTH Height: HEIGHT

**Comment by Jonaseli** [comment]
Mangler bare iconer for Handicap eller Charing Station etter #98

**Comment by norwen3** [comment]
jonas gjort
