### ISSUE TITLE
lag post siden

### ISSUE THREAD

**Issue by haros-dev** [Jonaseli/SE2020-Gruppe12#79]
denne oppgaven er relativt simpel
du skal lage en side som er basically prikk lik parkingspot detail, bare at det er en post
denne post-siden skal ha en knapp for å reservere parkeringsplassen (trenger ikke implementere funksjonaliteten, kun legge til en knapp)

siden skal også inkludere hva prisen på plassen er

**Comment by Jonaseli** [comment]
Denne forsvinner fra MVP, så closer.
