### ISSUE TITLE
Funksjonalitet for å lage objekter i terminal

### ISSUE THREAD

**Issue by Jonaseli** [Jonaseli/SE2020-Gruppe12#8]
Skal kunne lage et nytt parkeringsplass objekt/konto (bruker/selger) objekt fra terminalen. Dette kan vi da bruke til å
teste oppretting og sletting av objekter når den funksjonaliteten er laget.

**Comment by larseriktf** [comment]
Dette er jo veldig omfattende, skal vi close?

**Comment by Jonaseli** [comment]
Tenkte det var en grei måte å finne ut av hvilke variabler og metoder vi trengte osv. Vi har jo nå lagt ferdig repository med disse metodene, så kan godt close for min del. @42-Broenstudentavis
